### ISSUE TITLE
Linux QQNT安装QmsgNt插件后QQ无法正常启动

### ISSUE THREAD

**Issue by sectlying** [1244453393/QmsgNtClient#1]
Linux QQNT安装QmsgNt插件后QQ无法正常启动

错误日志
```
username@pc ~> qq --enable-logging
version_config_filename :/home/username/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/username/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/username/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[LiteLoader] Use LITELOADERQQNT_PROFILE environment variables: /home/username/.config/LiteLoader-Plugins
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: LLOneBot v3.27.3
[LiteLoader] Found plugin: QmsgNtClient v1.0.12
[LiteLoader] Found 2 plugins, start loading plugins.
llonebot websocket service started
llonebot websocket service started
Error: Attempted to register a second handler for 'llonebot_check_version'
A JavaScript error occurred in the main process
Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25406:26)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
    at Process.dlopen [as dlopenOrig] (/home/username/.config/LiteLoader-Plugins/plugins/LLOneBot/main/main.cjs:25407:24)
Gtk-Message: 01:01:44.337: Failed to load module "appmenu-gtk-module"
[13424:0730/010144.398354:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[13455:0730/010144.481353:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[13498:0730/010144.547484:WARNING:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
[13498:0730/010144.548122:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

···
系统版本: RockyLinux 9.4
桌面环境: KDE Plasma
LiteLoader版本: 1.1.2
QQNT版本: 3.2.10-25765
LLOnebot版本: 3.27.3

**Comment by 1244453393** [comment]
QmsgNtClient是为windwos准备的，linux可以尝试使用Docker方案https://github.com/1244453393/QmsgNtClient-NapCatQQ
